name: 'Release Changelog Builder'
description: 'Pulls all merged pull requests, and constructs the changelog for a release'
author: 'Mike Penz'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  configuration:
    required: true
    description: 'path to the configuration file'
    default: "configuration.json"
  path:
    description: 'the path to runt his action in'
  owner:
    description: 'the owner of the repository to create the changelog for'
  repo:
    description: 'the repository to create the changelog for'
  fromTag:
    description: 'the previous tag to compare against'
  toTag:
    description: 'the new tag created'
  ignorePreReleases:
    description: 'defines if only full releases should be considered to compare against (Only used if fromTag is not defined). E.g. for 1.0.1... 1.0.0-rc02 <- ignore, 1.0.0 <- pick'
    default: "false"
  token:
    description: 'the token to use to execute the git API requests'
outputs:
  changelog:
    description: The generated changelog as markdown.
runs:
  using: 'node12'
  main: 'dist/index.js'
