name: 'Release Changelog Builder'
description: 'A GitHub action that builds your release notes fast, easy and exactly the way you want.'
author: 'Mike Penz'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  configuration:
    description: 'Defines the relative path to the configuration file.'
  path:
    description: 'Defines the directory the repo is located in (checkout directory)'
  owner:
    description: 'Defines the owner of the repository to create the changelog for'
  repo:
    description: 'Defines the repository to create the changelog for'
  fromTag:
    description: 'Defines the previous tag to compare against'
  toTag:
    description: 'Defines the newly tag created'
  ignorePreReleases:
    description: 'Defines if the action will only use full releases to compare against (Only used if fromTag is not defined). E.g. for 1.0.1... 1.0.0-rc02 <- ignore, 1.0.0 <- pick'
    default: "false"
  failOnError:
    description: 'Defines if the action should result in a build failure, if an error was discovered'
    default: "false"
  token:
    description: 'Defines the token to use to execute the git API requests with, uses `env.GITHUB_TOKEN` by default'
outputs:
  changelog:
    description: Returns the generated changelog as markdown.
runs:
  using: 'node12'
  main: 'dist/index.js'
